# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50513c5df7a85fd207fc0fe5cdd3bda3f3924c05534202aaa399b0f270694b559c8e61bbcd3f548d8df0e115d4fea661637b3191c58b3e2423a7936f897ff332

test:
  secret_key_base: 2ceea4e8f74917baee79a4b40531f60d4fa014b4011c6a8c6d45c12764cb309a39bfba14bc6e9f6e05c382ba1128cfba21e94b2fc29322402b8e7042eab07070

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
